feat: 애플 로그인 기본 기능 구현
nbcamp/til-app pull request #23
Opened 2023-10-16 12:47 UTC by LeeJaeheee

- 프로젝트 기본 언어 Korean으로 변경
- Team, Bundle Identifier 변경(추후 논의 필요)
- 서버 연결 후 저장 로직 구현 필요함

resolve #4

2023-10-17 01:19 UTC, jinyongp approved these changes

2023-10-17 05:04 UTC, jinyongp requested changes

2023-10-17 05:04 UTC, jinyongp commented on TILApp/Views/AuthView/SignInViewController.swift
> +    (controller: ASAuthorizationController, didCompleteWithAuthorization authorization: ASAuthorization) {
```suggestion
    func authorizationController(
        controller: ASAuthorizationController,
        didCompleteWithAuthorization authorization: ASAuthorization
    ) {
```

보통 함수 이름하고 매개변수 사이에 공백이나 줄바꿈을 넣지 않아서 이렇게 작성하면 더 좋지 않을까 싶네요.

2023-10-17 05:04 UTC, jinyongp commented on TILApp/Views/AuthView/SignInViewController.swift
> +    func setAppleLoginButton() {
외부에서 호출하지 않을 함수나 속성은 private 키워드를 붙여주는 습관을 가지는게 좋아요.

2023-10-17 05:04 UTC, jinyongp commented on TILApp/Views/AuthView/SignInViewController.swift
> +    @objc func handleAuthorizationAppleIDButtonPress() {
```suggestion
    @objc private func handleAuthorizationAppleIDButtonPress() {
```

여기도 마찬가지로 private 붙일 수 있어요.

2023-10-17 06:05 UTC, LeeSeonQ approved these changes

2023-10-17 06:05 UTC, LeeSeonQ approved these changes

2023-10-25 17:02 UTC, jinyongp commented on TILApp/Views/AuthView/SignInViewController.swift
> +                provider: "Apple",
이거 전부 대문자로만 수정해주세요. 다른 플랫폼 Provider 오는거 보면 전부 대문자로 되어 있더라구요.

2023-10-26 12:17 UTC, LeeSeonQ approved these changes

2023-10-27 02:24 UTC, merged