[Feat] 홈 화면 UI 작성
nbcamp/til-app pull request #25
Opened 2023-10-17 12:53 UTC by LeeSeonQ

## 작업한 내용 설명

[FEATURE]: 홈 화면 UI 작성

UI 작성 및 ViewController 단일화

## UI 변경 작업물
<img width="307" alt="스크린샷 2023-10-19 오후 2 44 57" src="https://github.com/nbcamp/til-app/assets/139327412/20bff407-eb1a-41cd-b6ea-092811d5eac1">

<img width="302" alt="스크린샷 2023-10-19 오후 2 43 55" src="https://github.com/nbcamp/til-app/assets/139327412/800fb3a2-7ed3-43da-b4d1-28bc8542dc00">

<img width="308" alt="스크린샷 2023-10-19 오후 2 44 14" src="https://github.com/nbcamp/til-app/assets/139327412/1d5dc3ab-1dcb-430e-b6f0-ca7a1edec224">

---

resolve #1

2023-10-19 00:56 UTC, LeeJaeheee commented on TILApp/Views/HomeView/HomeViewController.swift
> +    private let registerBlogButton = {
커스텀 컴포넌트 병합되면 커스텀 버튼으로 변경해주세요!😁

2023-10-19 01:03 UTC, LeeJaeheee commented on TILApp/Views/HomeView/HomeViewController.swift
> +        imageView.tintColor = .systemTeal
에셋에 저희 메인 컬러 AccentColor로 추가해뒀으니 추후에 변경하시면 됩니다!

2023-10-19 01:03 UTC, LeeJaeheee approved these changes
👍👍

2023-10-19 06:26 UTC, jinyongp commented on TILApp/Views/HomeView/HomeViewController.swift
> +    private var TILComplete: Bool = false // TIL 작성 상태
이 부분은 나중에 변경할거라 수정 안하셔도 되지만, 변수 이름은 전부 전부 카멜 케이스로 작성해주세요.

2023-10-19 06:27 UTC, jinyongp commented on TILApp/Views/HomeView/HomeViewController.swift
> +    private var TILComplete: Bool = false // TIL 작성 상태
그리고 나중에 수정이 필요할 것으로 예상되는 부분은 `// TODO: 내용` 주석 남겨주시면 됩니다.

2023-10-19 06:28 UTC, jinyongp commented on TILApp/Views/HomeView/HomeViewController.swift
> +            print("TIL count out of range (1 to 10)")
병합 시에는 테스트 중에 사용헀던 print는 전부 제거해주시고 나중에 변경이 필요한 부분이라면 `// TODO: 설명` 주석 남겨주시면 됩니다.

2023-10-19 06:29 UTC, jinyongp requested changes
몇 가지만 유의해서 수정 부탁드려요~

2023-10-20 08:08 UTC, jinyongp approved these changes
고생하셨습니다.

2023-10-21 02:56 UTC, LeeJaeheee approved these changes

2023-10-23 05:22 UTC, merged