refactor: Then 적용, teamComponent 적용, TODO 주석 추가
nbcamp/til-app pull request #33
Opened 2023-10-20 17:17 UTC by LeeSeonQ

## 작업한 내용 설명
refactor: Then 적용, teamComponent 적용, TODO 주석 추가
내 정보 화면 코드 수정

## UI 변경 작업물
<img width="338" alt="스크린샷 2023-10-21 오전 2 13 48" src="https://github.com/nbcamp/til-app/assets/139327412/c17dad03-893e-4051-bc96-cca346ed3b23">

---

resolve #32

2023-10-21 14:42 UTC, jinyongp requested changes

2023-10-21 14:42 UTC, jinyongp commented on TILApp/Views/MyProfileViewController/MyProfileViewController.swift
>          countView.flex.layout()
setupUI()에 있어야하지 않을까 싶네요.

2023-10-21 14:42 UTC, jinyongp commented on TILApp/Views/MyProfileViewController/MyProfileViewController.swift
>          view.backgroundColor = .systemBackground
이 코드라인은 viewDidLoaded에 위치해도 되겠네요.

2023-10-24 02:59 UTC, jinyongp approved these changes

2023-10-24 03:48 UTC, LeeJaeheee approved these changes

2023-10-24 07:36 UTC, merged