[Feat] 커뮤니티 화면 UI 작성
nbcamp/til-app pull request #34
Opened 2023-10-21 03:49 UTC by LeeJaeheee

## UI 변경 작업물

UI 변경을 포함한 작업이라면 여기에 스크린샷을 남겨주세요.
<img
  src="https://github.com/nbcamp/til-app/assets/74818845/24dcf8a5-0d32-467e-bd52-e284f081ac17"
  width="400" />
---

resolve #8

2023-10-21 06:04 UTC, LeeSeonQ approved these changes
고생 많으셨습니다.
나중에 태그위치를 생각해서 서치바를 탭바에 놓는것도 생각해보면 좋을 것 같네요 👍

2023-10-21 07:20 UTC, jinyongp requested changes
이 화면에서 사용하는 컴포넌트 클래스 하나마다 하나의 파일로 분리 부탁드려요. 나중에는 CustomComponents 파일을 지워야해서...

Views -> LaunchScreen.storyboard 아래 Components 폴더 생성해서 한 클래스 당 하나의 파일로 생성해주시면 됩니다.

2023-10-21 07:20 UTC, jinyongp commented on TILApp/Views/CommunityView/CommunityViewController.swift
> +        return cell
이 부분은 수정해야할 거 같아요... CustomCommunityTILView의 내부 구현 뿐만 아니라 CustomUserView의 내부 구현 동작까지 알아야 하는거라 인터페이스가 그리 좋지 못해보여서요. CustomCommunityTILView을 사용하려면 무조건 setup을 두번 호출해야하는 걸 알아야해서... CustomCommunityTILView에서 userView와 TILView에 데이터를 전달하는 걸 하나로 통합하고 CommunityTableViewCell에서도 setup 함수로 하나의 API로 설정할 수 있도록 하는게 좋을 거 같아요.

그리고 TILView 변수이름은 카멜케이스로 작성해주세요. 그냥 tilView도 괜찮을 거 같네요.

2023-10-21 07:20 UTC, jinyongp commented on TILApp/Views/CommunityView/CommunityViewController.swift
> +    private let tableView = UITableView()
```suggestion
    private lazy var tableView = UITableView().then {    		
        $0.dataSource = self
        $0.delegate = self
        $0.register(CommunityTableViewCell.self, forCellReuseIdentifier: "CommunityTableViewCell")
    }
```

이렇게 작성하면 더 깔끔할거 같아요 🙂

2023-10-21 07:20 UTC, jinyongp commented on TILApp/Views/CommunityView/CommunityTableViewCell.swift
> +class CommunityTableViewCell: UITableViewCell {
상속할 의도가 있는 클래스가 아니라면 `final` 키워드를 붙여주세요! (ref - Method Dispatching: Static, Dynamic)

2023-10-23 01:51 UTC, LeeSeonQ approved these changes

2023-10-23 02:55 UTC, LeeSeonQ approved these changes

2023-10-23 04:07 UTC, jinyongp commented
충돌 해결해주시면 병합할게요.

2023-10-23 07:21 UTC, merged