[Feat] 사용자 정보 수정 화면 UI 작성
nbcamp/til-app pull request #35
Opened 2023-10-21 13:21 UTC by LeeSeonQ

## 작업한 내용 설명
[Feat] 사용자 정보 수정 화면 UI 작성

## UI 변경 작업물
<img width="327" alt="스크린샷 2023-10-21 오후 10 15 02" src="https://github.com/nbcamp/til-app/assets/139327412/7cd2b864-ce92-495e-aa53-7761ddc9ad26">

---

resolve #17

2023-10-21 13:33 UTC, jinyongp requested changes

2023-10-21 13:33 UTC, jinyongp commented on TILApp/Views/MyProfileViewController/ProfileEditViewController.swift
> +class ProfileEditViewController: UIViewController {
특별히 상속을 하려는 목적이 아니라면 `final` 키워드를 붙여주세요~ (ref: Method Dispatching)

2023-10-21 13:33 UTC, jinyongp commented on TILApp/Views/MyProfileViewController/ProfileEditViewController.swift
> +        componentView.flex.layout()
이 라인도 setupUI에 가야할 거 같네요.

2023-10-21 13:35 UTC, jinyongp commented on TILApp/Views/MyProfileViewController/ProfileEditViewController.swift
> +    private lazy var editProfileImageView = UIImageView().then {
여기 빈 곳이 person 아이콘 들어가고 아래에 editProfieButton에 카메라 아이콘 들어가는게 어떨까요? 그리고 배경화면 좀더 밝게 하는게 좋을거 같아요. 회색이 너무 강렬해보이네요.

2023-10-23 00:00 UTC, LeeJaeheee approved these changes

2023-10-24 01:31 UTC, LeeJaeheee approved these changes

2023-10-24 03:07 UTC, merged