[Feat] 블로그 정보 편집 화면 UI 작성
nbcamp/til-app pull request #44
Opened 2023-10-26 10:05 UTC by LeeJaeheee

## 작업한 내용 설명

- 블로그 정보 편집 화면 UI 작성
- 블로그 관리 페이지 연결
- 블로그 목록 관련 컴포넌트 variant 생성

## UI 변경 작업물

<img src="https://github.com/nbcamp/til-app/assets/74818845/a5944ae7-eb6d-449e-88ca-d8cc6b724d4e" width="400">
<img src="https://github.com/nbcamp/til-app/assets/74818845/a9031dc7-f798-47db-9e64-b4716e827cdb" width="400">

---

resolve #15

2023-10-26 12:32 UTC, LeeSeonQ approved these changes

2023-10-26 12:37 UTC, jinyongp requested changes

2023-10-26 12:37 UTC, jinyongp commented on TILApp/Utilities/CustomComponents.swift
> +                break
primaryLabel을 지워줘야할 거 같네요.

2023-10-26 12:37 UTC, jinyongp commented on TILApp/Views/MyProfileViewController/BlogEditViewController.swift
> +            print(index, tagData[index])
debugPrint

2023-10-27 02:33 UTC, jinyongp approved these changes

2023-10-27 02:33 UTC, merged