Feature/7
nbcamp/til-app pull request #46
Opened 2023-10-27 10:53 UTC by LeeJaeheee

## 작업한 내용 설명

- 커스텀 컴포넌트 파일 분리
- 팔로우 버튼 variant 설정 및 관련 컴포넌트들 수정
- segmented control 높이 수정 및 커스텀 삭제
- 커스텀 텍스트필드read-only 함수 추가
- CustomLargeBorderButton variant 추가 및 블로그 수정 페이지에 적용(체크마크 추가) 

## UI 변경 작업물
<img src="https://github.com/nbcamp/til-app/assets/74818845/d9cf3b1c-4a31-4607-9552-c3ce628ab86f" width="200">
<img src="https://github.com/nbcamp/til-app/assets/74818845/3ee8b4af-76ec-4feb-8624-6d1bbe126252" width="200">

---

resolve #7

2023-10-27 12:58 UTC, LeeSeonQ approved these changes

2023-10-27 13:03 UTC, LeeSeonQ approved these changes

2023-10-27 13:05 UTC, jinyongp requested changes

2023-10-28 03:06 UTC, jinyongp requested changes
충돌 해결 부탁드려요!

2023-10-28 03:06 UTC, jinyongp commented on TILApp/Views/Shared/Components/CustomTextFieldView.swift
> +            }
readOnly를 설정했을 때만 아니라 다시 해제했을 때도 원래도 다시 동작하도록 해야 될 듯 하네요.

```suggestion
            textField.isUserInteractionEnabled = !readOnly
            textField.textColor = readOnly ? .systemGray2 : 원래색
```

이런 식으로...

2023-10-28 05:51 UTC, merged