[Feat] 블로그 등록, 수정, 삭제 기능 연결 #47
nbcamp/til-app pull request #58
Opened 2023-10-29 13:59 UTC by LeeJaeheee

## 작업한 내용 설명

- 블로그 등록 페이지 유효성 검사 추가 및 기능 연결
- 블로그 목록 페이지 연결
- 키워드 등록 및 수정 페이지 유효성 검사 추가 및 기능 연결
- 블로그 수정 페이지 유효성 검사 추가 및 기능 연결
- 블로그 삭제 기능 연결
- CustomTextField 관련 UI 및 기능 자잘한 수정
- 키워드, 태그 CRUD 뷰모델 작성 및 연결

- 대표 블로그 설정 관련 수정 필요 
- 유저 정보 및 블로그 API 불러오는 시점 조절 필요 (기능 연결 완료 후)
- TODO에 적어놓은 RSS 자동완성 함수 연결 필요

---

resolve #47

2023-10-29 16:40 UTC, jinyongp requested changes
기네요... ㅋㅋ 좋습니다

2023-10-29 16:40 UTC, jinyongp commented on TILApp/ViewModels/BlogViewModel.swift
> +    }
임시로 keyword 생성 및 관리하는 로직인데 BlogViewModel에 있는 건 좀 이상해보이네요. 차라리 Builder 패턴으로 별도의 KeywordBuilder 같은 클래스로 빼서 만들면 어떨런지... 

https://refactoring.guru/design-patterns/builder/swift/example

2023-10-29 16:40 UTC, jinyongp commented on TILApp/Resources/SceneDelegate.swift
> +                }
authenticated가 false라면 SignInViewController 페이지 보여주는건 맞고,
true여도 토큰이 만료된 경우가 있거든요 (저번에 겪으셨던 거처럼)

이 로직은 AuthViewModel의 속성을 직접적으로 변경하는 로직이니 이러지 마시고, AuthViewModel에 별도의 메서드로 분리해주세요. (애초에 var user: User?가 아니라 private(var) user: User? 여야 하는데 실수했네요.)

내부에서 응답이 잘 왔을 경우, 내부 user 속성 업데이트 해주시고 에러 발생하면 로그아웃 후 SignInViewController 페이지로 이동하도록 해주시면 깔끔하게 처리될 듯 합니다.

2023-10-29 16:40 UTC, jinyongp commented on TILApp/Models/Blog.swift
> +    }
이 로직은 필요 없을거에요. 자동으로 생성되는 생성자이거니와... 나머지도 전부 Equtable한 형식이라서...

2023-10-29 16:40 UTC, jinyongp commented on TILApp/Views/HomeView/HomeViewController.swift
> +        $0.text = "\(String(describing: AuthViewModel.shared.user?.username))님, 안녕하세요!"
AuthViewModel.shared.user를 두 군데에서 사용하니까 차라리 별도의 속성으로 분리하면 더 깔끔해질 거 같아요. `private let user = AuthViewModel.shared.user`

2023-10-29 16:40 UTC, jinyongp commented on TILApp/Views/HomeView/HomeViewController.swift
> +        hiLabel.text = "\(username)님, 안녕하세요!"
이렇게 일부분만 가리기 보다는 아까 했었던 SceneDelegate에서 profile 정보 가져올 때까지 로딩 화면 띄워주는게 필요하겠네요...

2023-10-29 16:40 UTC, jinyongp commented on TILApp/Views/MyProfileViewController/BlogEditViewController.swift
> +        blogViewModel.update(blog, .init(name: blogNameTextField.mainText, keywords: blogViewModel.keywords), onSuccess: { [weak self] updatedBlog in
여기 아마 lint 경고 뜰텐데... 적절하게 줄바꿈 해주시면 읽기 편할 듯 합니다. (ViewModel 코드 참고하시면 될거에요.)

2023-10-29 16:40 UTC, jinyongp commented on TILApp/ViewModels/BlogViewModel.swift
> +
API 연결 나중에 하시려는거죠?

2023-10-29 16:40 UTC, jinyongp commented on TILApp/Views/MyProfileViewController/BlogEditViewController.swift
> +                blogNameTextField.validationText = ""
한 자라도 작성하면 유효하게 해도 되지 않을까요?

2023-10-30 08:45 UTC, LeeSeonQ approved these changes

2023-10-30 08:46 UTC, merged