[Refactor] RSS Model, ViewModel 작성 및 CalendarViewController 분리 #6
nbcamp/til-app pull request #74
Opened 2023-10-31 11:33 UTC by wjdehdry3

## 작업한 내용 설명

캘린더뷰컨트롤러에 rss파싱하는 부분 같이 있는걸 뷰모델과 모델로 분리작업

## UI 변경 작업물

![Simulator Screenshot - iPhone 15 Pro - 2023-10-31 at 20 31 18](https://github.com/nbcamp/til-app/assets/64249456/101b1094-3bd4-43ef-ab4f-f61406b1b3f9)

resolve #6

2023-10-31 23:05 UTC, LeeSeonQ approved these changes

2023-11-07 07:34 UTC, jinyongp requested changes

2023-11-07 07:34 UTC, jinyongp commented on TILApp/Views/CalendarView/CalendarViewController.swift
>      override func viewWillAppear(_ animated: Bool) {
```suggestion
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.isNavigatioinBarHidden = true
```

isNavigatioinBarHidden은 true로 설정해야 네비게이션바가 사라집니다.

2023-11-07 07:34 UTC, jinyongp commented on TILApp/Views/CalendarView/CalendarViewController.swift
>      override func viewDidLayoutSubviews() {
```suggestion
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        calendarFlexView.flex.direction(.column).define {
            $0.addItem(calendarResultContent).alignItems(.center)
            $0.addItem(calendarView).marginLeft(20).marginRight(20).aspectRatio(1)
            $0.addItem().grow(1).define { flex in
                flex.view?.addSubview(tableView)
            }
        }

        calendarFlexView.pin.all(view.pin.safeArea)
        calendarFlexView.flex.layout()
        tableView.pin.all()
    }
```

tableView 말고 빈 UIView를 추가하였습니다. tableView 위치는 아래서 잡아줬어요.
이러면 바텀탭바 안 가릴거에요.

2023-11-07 07:34 UTC, jinyongp commented on TILApp/Views/CalendarView/CalendarViewController.swift
웬만한 주석 다 지워주세요.

2023-11-07 07:53 UTC, LeeJaeheee approved these changes

2023-11-07 08:51 UTC, LeeSeonQ approved these changes

2023-11-07 11:37 UTC, merged